"""
YadaCoin Open Source License (YOSL) v1.1

Copyright (c) 2017-2025 Matthew Vogel, Reynold Vogel, Inc.

This software is licensed under YOSL v1.1 – for personal and research use only.
NO commercial use, NO blockchain forks, and NO branding use without permission.

For commercial license inquiries, contact: info@yadacoin.io

Full license terms: see LICENSE.txt in this repository.
"""

"""
Handlers required by the web operations
"""

import datetime
import hashlib
import json
import time
import uuid

import jwt

from yadacoin.core.config import Config
from yadacoin.core.graphutils import GraphUtils as GU
from yadacoin.http.base import BaseHandler

challenges = {}


class HomeHandler(BaseHandler):
    async def get(self):
        """
        Serve the main node dashboard, or redirect to the pool dashboard
        when peer_type is 'pool'.
        """
        if getattr(self.config, "peer_type", None) == "pool":
            return self.redirect("/pool")
        self.render("dashboard.html")


class MultifactorAuthHandler(BaseHandler):
    async def get(self):
        redirect = self.get_query_argument("redirect", None)
        origin = self.get_query_argument("origin")
        if not origin:
            return '{"error": "origin not in query params"}', 400
        self.set_header("Access-Control-Allow-Origin", origin)
        self.set_header("Access-Control-Allow-Credentials", "true")
        self.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.set_header("Access-Control-Expose-Headers", "Content-Type")
        self.set_header(
            "Access-Control-Allow-Headers",
            "Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, Cache-Control",
        )
        self.set_header("Access-Control-Max-Age", 600)
        config = self.config
        rid = self.get_query_argument("rid")
        if not rid:
            return '{"error": "rid not in query params"}', 400

        txn_id = self.get_query_argument("id")

        cookie = self.get_secure_cookie("signin_code")
        if cookie:
            cookie = cookie.decode("utf-8")
        else:
            cookie = str(uuid.uuid4())
            self.set_secure_cookie("signin_code", cookie)

        result = await GU().verify_message(
            rid, cookie, config.public_key, txn_id.replace(" ", "+")
        )

        if result[1]:
            self.set_secure_cookie("rid", rid)

            username = await self.config.mongo.async_db.name_server.find_one(
                {"rid": rid}
            )
            self.set_secure_cookie(
                "username", username["txn"]["relationship"]["their_username"]
            )

            if redirect:
                return self.redirect(redirect)
            else:
                return self.render_as_json({"authenticated": True})

        return self.render_as_json({"authenticated": False})


class GenerateChallengeHandler(BaseHandler):
    async def get(self):
        challenge = uuid.uuid4()
        await self.config.mongo.async_site_db.challenges.update_one(
            {"rid": self.get_query_argument("rid")},
            {"$set": {"rid": self.get_query_argument("rid"), "challenge": challenge}},
            upsert=True,
        )

        return self.render_as_json({"challenge": challenge})


class LoginHandler(BaseHandler):
    async def get(self):
        origin = self.get_query_argument("origin")
        if not origin:
            return '{"error": "origin not in query params"}', 400

        # TODO: protect this endpoint with information that could only be generated by the identity!
        self.set_header("Access-Control-Allow-Origin", origin)
        self.set_header("Access-Control-Allow-Credentials", "true")
        self.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.set_header("Access-Control-Expose-Headers", "Content-Type")
        self.set_header(
            "Access-Control-Allow-Headers",
            "Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, Cache-Control",
        )
        self.set_header("Access-Control-Max-Age", 600)

        challenge = await self.config.mongo.async_site_db.challenges.find_one(
            {"rid": self.get_query_argument("rid")}
        )

        alias = Config.generate(username=challenge)
        alias_identity = alias.get_identity()

        payload = {
            "timestamp": time.time(),
            "exp": datetime.datetime.utcnow()
            + datetime.timedelta(seconds=int(self.config.web_jwt_expiry)),
            "alias": alias_identity,
        }

        self.encoded = jwt.encode(
            payload, self.config.jwt_secret_key, algorithm="ES256"
        )
        await self.config.mongo.async_site_db.web_tokens.update_one(
            {"token": self.encoded, "rid": self.get_query_argument("rid")},
            {
                "$set": {
                    "token": self.encoded,
                    "rid": self.get_query_argument("rid"),
                    "payload": payload,
                }
            },
            upsert=True,
        )

        self.render_as_json({"token": self.encoded, "wif": alias.wif})


class RemoteMultifactorAuthHandler(BaseHandler):
    async def post(self):
        args = json.loads(self.request.body.decode("utf-8"))
        origin = args.get("origin", "*")
        redirect = args.get("redirect")
        signin_code = args.get("signin_code")

        if not signin_code:
            return self.render_as_json({"error": "missing params"}), 400
        self.set_header("Access-Control-Allow-Origin", origin)
        self.set_header("Access-Control-Allow-Credentials", "true")
        self.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.set_header("Access-Control-Expose-Headers", "Content-Type")
        self.set_header(
            "Access-Control-Allow-Headers",
            "Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, Cache-Control",
        )
        self.set_header("Access-Control-Max-Age", 600)

        result = await self.config.mongo.async_db.verify_message_cache.find_one(
            {"message.signIn": signin_code}
        )

        if result:
            self.set_secure_cookie("rid", result["rid"])

            username = await self.config.mongo.async_db.name_server.find_one(
                {"rid": result["rid"]}
            )
            self.set_secure_cookie(
                "username", username["txn"]["relationship"]["their_username"]
            )

            result = await self.config.mongo.async_db.verify_message_cache.delete_one(
                {"message.signIn": signin_code}
            )
            if redirect:
                return self.redirect(redirect)
            else:
                return self.render_as_json({"authenticated": True})

        return self.render_as_json({"authenticated": False})


class TwoFactorAuthHandler(BaseHandler):
    async def post(self):
        """
        :return:
        """
        args = json.loads(self.request.body.decode("utf-8"))
        origin = args.get("origin", "*")
        redirect = args.get("redirect")
        auth_code = args.get("signin_code")

        if not auth_code:
            return self.render_as_json({"error": "missing params"}), 400
        self.set_header("Access-Control-Allow-Origin", origin)
        self.set_header("Access-Control-Allow-Credentials", "true")
        self.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.set_header("Access-Control-Expose-Headers", "Content-Type")
        self.set_header(
            "Access-Control-Allow-Headers",
            "Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, Cache-Control",
        )
        self.set_header("Access-Control-Max-Age", 600)

        shared_secrets = self.config.GU.get_shared_secrets_by_rid(
            self.get_secure_cookie("rid").decode()
        )
        authenticated = False
        for shared_secret in shared_secrets:
            hashed_shared_secret = hashlib.sha256(shared_secret).hexdigest()
            thirty_rounded_time = str(int(time.time() // 30 * 30))
            result = int(
                hashlib.sha256(
                    (thirty_rounded_time + hashed_shared_secret).encode()
                ).hexdigest(),
                16,
            ) % (10**6)
            if "000000{}".format(result)[-6:] == auth_code:
                authenticated = True
                self.set_secure_cookie("2fa", "true")
                break

        if redirect:
            return self.redirect(redirect)
        else:
            return self.render_as_json({"authenticated": authenticated})


class LogoutHandler(BaseHandler):
    def get(self):
        redirect = self.get_query_argument("redirect", None)

        if self.get_secure_cookie("signin_code"):
            self.set_secure_cookie("signin_code", "")

        if self.get_secure_cookie("rid"):
            self.set_secure_cookie("rid", "")

        if self.get_secure_cookie("username"):
            self.set_secure_cookie("username", "")

        if redirect:
            self.redirect(redirect)
        else:
            self.render_as_json({"authenticated": False})


class AppHandler(BaseHandler):
    async def get(self):
        """
        :return:
        """
        self.render("app.html")


class GetRecoveryTransaction(BaseHandler):
    async def get(self):
        """
        :return:
        """
        rid = self.get_query_argument("rid")
        txn = await self.config.mongo.async_db.blocks.find_one(
            {"transactions.rid": rid}, {"_id": 0}
        )
        if not txn:
            txn = await self.config.mongo.async_db.miner_transactions.find_one(
                {"rid": rid}, {"_id": 0}
            )
        return self.render_as_json(txn)


WEB_HANDLERS = [
    (r"/", HomeHandler),
    (r"/node-dashboard", HomeHandler),
    (r"/mfa", MultifactorAuthHandler),
    (r"/login", LoginHandler),
    (r"/rmfa", RemoteMultifactorAuthHandler),
    (r"/2fa", TwoFactorAuthHandler),
    (r"/logout", LogoutHandler),
    (r"/app", AppHandler),
    (r"/get-recovery-transaction", GetRecoveryTransaction),
]
